// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNI9RIb-GciCpHUhl8KhDTeN5hQmnYMlI',
    appId: '1:313799665754:web:2e271e508ab87a33d49063',
    messagingSenderId: '313799665754',
    projectId: 'first-flutter-1ccf4',
    authDomain: 'first-flutter-1ccf4.firebaseapp.com',
    storageBucket: 'first-flutter-1ccf4.firebasestorage.app',
    measurementId: 'G-BRCXRVLZRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMN8VFwjCjE2eudlQe-M2V_XPXkvGAymk',
    appId: '1:313799665754:android:8e3790642d1361fbd49063',
    messagingSenderId: '313799665754',
    projectId: 'first-flutter-1ccf4',
    storageBucket: 'first-flutter-1ccf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzj5Go9TrxOHE_i4RfugUVMe6zXTS2dSI',
    appId: '1:313799665754:ios:935192abed75fd4dd49063',
    messagingSenderId: '313799665754',
    projectId: 'first-flutter-1ccf4',
    storageBucket: 'first-flutter-1ccf4.firebasestorage.app',
    iosClientId: '313799665754-a7psj5o5182mgimbripcptb25t8tnt4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialSiteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzj5Go9TrxOHE_i4RfugUVMe6zXTS2dSI',
    appId: '1:313799665754:ios:935192abed75fd4dd49063',
    messagingSenderId: '313799665754',
    projectId: 'first-flutter-1ccf4',
    storageBucket: 'first-flutter-1ccf4.firebasestorage.app',
    iosClientId: '313799665754-a7psj5o5182mgimbripcptb25t8tnt4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialSiteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNI9RIb-GciCpHUhl8KhDTeN5hQmnYMlI',
    appId: '1:313799665754:web:01e488de16d571c4d49063',
    messagingSenderId: '313799665754',
    projectId: 'first-flutter-1ccf4',
    authDomain: 'first-flutter-1ccf4.firebaseapp.com',
    storageBucket: 'first-flutter-1ccf4.firebasestorage.app',
    measurementId: 'G-XW4KJRP9N5',
  );
}
